# Generated by Django 5.1.2 on 2024-10-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
