# Generated by Django 5.1.2 on 2024-11-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='amount',
            new_name='price',
        ),
    ]
